DROP TABLE SYSTEM_USERS CASCADE CONSTRAINTS;
DROP TABLE INTERACTION_TYPES CASCADE CONSTRAINTS;
DROP TABLE CONSERVATION_RESERVES CASCADE CONSTRAINTS;
DROP TABLE RESEARCH_FACILITIES CASCADE CONSTRAINTS;
DROP TABLE LIVING_SPECIMENS CASCADE CONSTRAINTS;
DROP TABLE THREAT_TYPES CASCADE CONSTRAINTS;

DROP SEQUENCE SEQUENCE_RESERVES;
DROP SEQUENCE SEQ_BIOMES;
DROP SEQUENCE SEQ_ECOLOGICAL_INTERACTIONS;
DROP SEQUENCE SEQ_GEOGRAPHICAL_REGIONS;
DROP SEQUENCE SEQ_INTERACTION_TYPES;
DROP SEQUENCE SEQ_LIVING_SPECIMENS;
DROP SEQUENCE SEQ_ORGANISMS;
DROP SEQUENCE SEQ_REGIONAL_THREAT_LOGS;
DROP SEQUENCE SEQ_RESEARCH_FACILITIES;
DROP SEQUENCE SEQ_SIGHTING_LOGS;
DROP SEQUENCE SEQ_SPECIES_ENCYCLOPEDIA;
DROP SEQUENCE SEQ_SPECIES_PROFILES;
DROP SEQUENCE SEQ_SYSTEM_USERS;
DROP SEQUENCE SEQ_TAGS;
DROP SEQUENCE SEQ_TAXONOMIC_RANKS;
DROP SEQUENCE SEQ_THREAT_TYPES;

COMMIT;
EXIT;
